name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "*/12 * * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Fetch user's GitHub profile
        id: fetch_profile
        run: |
          USER_THEME=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/${{ github.repository_owner }} | jq -r '. | if (.site_admin == false) then . | . | .is_dark_mode | (. == "true") else .is_dark_mode | (. == "true") end')
          echo "::set-output name=theme::$USER_THEME"

      - name: Determine palette based on user's GitHub theme
        id: determine_palette
        run: |
          THEME="$([[ '${{ steps.fetch_profile.outputs.theme }}' == 'true' ]] && echo 'github-dark' || echo 'github-light')"
          echo "::set-output name=palette::$THEME"

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=${{ steps.determine_palette.outputs.palette }}

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
